# Task 3 — Generative AI Recommendation Articles with Qwen

This notebook uses `clustered_amazon_reviews.csv` from Task 2.

### Pipeline
**Task 2 categories → product statistics → weighted ranking → negative reviews → TF-IDF complaint themes → grounded evidence → Qwen2.5-1.5B-Instruct → recommendation articles → evaluation**

Make sure Task 2 contains meaningful `meta_category` names before running this notebook.

## 1. Imports and data

In [1]:
# Run once if required:
# !pip install -q -U transformers accelerate torch scikit-learn

import pandas as pd
import numpy as np
import re
import torch
from pathlib import Path
from sklearn.feature_extraction.text import TfidfVectorizer
from transformers import AutoTokenizer, AutoModelForCausalLM

df = pd.read_csv("clustered_reviews.csv", low_memory=False)

print("Shape:", df.shape)
display(df.head())

Shape: (60841, 11)

,id,product_name,name,brand,categories,source,reviews.rating,reviews.title,reviews.text,kmeans_cluster,kmeans_category
0,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...","All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...",1429_1.csv,5.0,Kindle,This product so far has not disappointed. My c...,0,Fire Tablets
1,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...","All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...",1429_1.csv,5.0,very fast,great for beginner or experienced person. Boug...,0,Fire Tablets
2,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...","All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...",1429_1.csv,5.0,Beginner tablet for our 9 year old son.,Inexpensive tablet for him to use and learn on...,0,Fire Tablets
3,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...","All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...",1429_1.csv,4.0,Good!!!,I've had my Fire HD 8 two weeks now and I love...,0,Fire Tablets
4,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...","All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...",1429_1.csv,5.0,Fantastic Tablet for kids,I bought this for my grand daughter when she c...,0,Fire Tablets

## 2. Validate and clean the Task 2 output

In [4]:
required = [
    "product_name", "kmeans_cluster", "kmeans_category",
    "reviews.text", "reviews.rating"
]

missing = [x for x in required if x not in df.columns]

if missing:
    raise ValueError(f"Missing columns: {missing}")

data = df.dropna(subset=required).copy()

if data["kmeans_category"].astype(str).str.contains(
    "RENAME_kmeans_cluster", na=False
).any():
    print("WARNING: Rename Task 2 kmeans_clusters before final generation.")

# Product names are cleaned in the next step.
# Keep the original `name` column here for traceability.
if "name" not in data.columns:
    raise ValueError("Missing required product column: name")

def clean_review(x):
    x = str(x).replace("\n", " ").replace("\r", " ")
    return re.sub(r"\s+", " ", x).strip()

data["review_clean"] = data["reviews.text"].apply(clean_review)

print("Rows:", len(data))
print("categories:", data["kmeans_category"].nunique())
print("Products:", data["product_name"].nunique())

Rows: 55611
categories: 6
Products: 69

## 3. Clean Product Names

The raw Amazon `name` field can contain inconsistent spacing, HTML fragments, duplicated punctuation, and other formatting noise.

We keep the original product name and create a separate `product_name_clean` column for analysis.

This cleaning step does **not** affect Task 2 clustering; it is used only for Task 3 product statistics and recommendation output.

In [5]:
from html import unescape

def clean_product_name(name):
    if pd.isna(name):
        return np.nan

    name = unescape(str(name))

    # Remove HTML tags
    name = re.sub(r"<[^>]+>", " ", name)

    # Replace line breaks/tabs with spaces
    name = re.sub(r"[\n\r\t]+", " ", name)

    # Remove repeated punctuation
    name = re.sub(r"([,;:/|\\-])\1+", r"\1", name)

    # Remove spaces before punctuation
    name = re.sub(r"\s+([,;:])", r"\1", name)

    # Normalize whitespace
    name = re.sub(r"\s+", " ", name)

    # Remove leading/trailing punctuation and spaces
    name = name.strip(" ,;:-_|")

    return name.strip()


# Always create a clean product-name column from the original name
if "name" not in data.columns:
    raise ValueError(
        "The dataset does not contain the original 'name' column."
    )

data["product_name_clean"] = (
    data["name"]
    .apply(clean_product_name)
)

# Convert empty strings to NaN
data["product_name_clean"] = (
    data["product_name_clean"]
    .replace("", np.nan)
)

# Remove rows without a usable product name
before = len(data)

data = data.dropna(
    subset=["product_name_clean"]
).copy()

after = len(data)

# Use the cleaned name throughout Task 3
PRODUCT_COLUMN = "product_name_clean"

print("Rows removed because product name was empty:", before - after)
print("Unique original product names:", data["name"].nunique())
print("Unique cleaned product names:", data["product_name_clean"].nunique())

display(
    data[
        ["name", "product_name_clean"]
    ]
    .drop_duplicates()
    .head(20)
)

Rows removed because product name was empty: 1563
Unique original product names: 119
Unique cleaned product names: 114

,name,product_name_clean
0,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...","All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,..."
2814,Kindle Oasis E-reader with Leather Charging Co...,Kindle Oasis E-reader with Leather Charging Co...
2881,"Amazon Kindle Lighted Leather Cover,,,\r\nAmaz...","Amazon Kindle Lighted Leather Cover, Amazon Ki..."
2883,"Amazon Kindle Lighted Leather Cover,,,\r\nKind...","Amazon Kindle Lighted Leather Cover, Kindle Ke..."
2884,"Kindle Keyboard,,,\r\nKindle Keyboard,,,","Kindle Keyboard, Kindle Keyboard"
2905,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...","All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,..."
3051,"Fire HD 8 Tablet with Alexa, 8 HD Display, 32 ...","Fire HD 8 Tablet with Alexa, 8 HD Display, 32 ..."
3065,Amazon 5W USB Official OEM Charger and Power A...,Amazon 5W USB Official OEM Charger and Power A...
3266,"All-New Kindle E-reader - Black, 6 Glare-Free ...","All-New Kindle E-reader - Black, 6 Glare-Free ..."
3478,"Amazon Kindle Fire Hd (3rd Generation) 8gb,,,\...","Amazon Kindle Fire Hd (3rd Generation) 8gb, Am..."
3480,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...","Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes..."
14446,Kindle Oasis E-reader with Leather Charging Co...,Kindle Oasis E-reader with Leather Charging Co...
14452,Amazon - Kindle Voyage - 4GB - Wi-Fi + 3G - Bl...,Amazon - Kindle Voyage - 4GB - Wi-Fi + 3G - Bl...
14477,Amazon - Kindle Voyage - 4GB - Wi-Fi + 3G - Bl...,Amazon - Kindle Voyage - 4GB - Wi-Fi + 3G - Bl...
14478,"Fire HD 8 Tablet with Alexa, 8 HD Display, 16 ...","Fire HD 8 Tablet with Alexa, 8 HD Display, 16 ..."
14484,Amazon Standing Protective Case for Fire HD 6 ...,Amazon Standing Protective Case for Fire HD 6 ...
14485,Certified Refurbished Amazon Fire TV (Previous...,Certified Refurbished Amazon Fire TV (Previous...
14488,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...
15526,Amazon Kindle Touch Leather Case (4th Generati...,Amazon Kindle Touch Leather Case (4th Generati...
15529,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...","Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16..."

## 4. Rating sentiment

We use the same rating interpretation as Task 1:

- 1–2 → negative
- 3 → neutral
- 4–5 → positive

In [6]:
def rating_sentiment(rating):
    if rating <= 2:
        return "negative"
    elif rating == 3:
        return "neutral"
    return "positive"

data["sentiment"] = data["reviews.rating"].apply(rating_sentiment)

display(data["sentiment"].value_counts().to_frame())

           count
sentiment
positive   49500
neutral     2381
negative    2167

## 5. Category statistics

In [8]:
category_stats = (
    data.groupby("kmeans_category")
    .agg(
        review_count=("reviews.text", "count"),
        product_count=(PRODUCT_COLUMN, "nunique"),
        average_rating=("reviews.rating", "mean")
    )
    .sort_values("review_count", ascending=False)
)

display(category_stats.style.format({"average_rating": "{:.2f}"}))

## 6. Product statistics

In [9]:
product_stats = (
    data.groupby(["kmeans_category", PRODUCT_COLUMN])
    .agg(
        review_count=("reviews.rating", "count"),
        average_rating=("reviews.rating", "mean"),
        positive_reviews=("sentiment", lambda x: (x == "positive").sum()),
        neutral_reviews=("sentiment", lambda x: (x == "neutral").sum()),
        negative_reviews=("sentiment", lambda x: (x == "negative").sum())
    )
    .reset_index()
)

for s in ["positive", "neutral", "negative"]:
    product_stats[s + "_pct"] = (
        product_stats[s + "_reviews"]
        / product_stats["review_count"] * 100
    )

display(
    product_stats.sort_values("review_count", ascending=False).head(20)
)

,kmeans_category,product_name_clean,review_count,average_rating,positive_reviews,neutral_reviews,negative_reviews,positive_pct,neutral_pct,negative_pct
75,Fire Tablets,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",10751,4.451772,9745,683,323,90.642731,6.352897,3.004372
80,"Household, Office & Pets",AmazonBasics AAA Performance Alkaline Batterie...,8336,4.447817,7174,359,803,86.060461,4.306622,9.632917
79,"Household, Office & Pets",AmazonBasics AA Performance Alkaline Batteries...,3724,4.453276,3206,175,343,86.090226,4.699248,9.210526
23,E-readers & Kindle,Amazon Kindle Paperwhite - eBook reader - 4 GB...,2928,4.771858,2849,49,30,97.301913,1.673497,1.024590
113,Smart Speakers & Echo,"Echo (White), Echo (White)",2898,4.678054,2763,100,35,95.341615,3.450656,1.207729
47,Fire Tablets,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",2814,4.586709,2667,93,54,94.776119,3.304904,1.918977
104,Smart Speakers & Echo,"Amazon Fire Tv, Amazon Fire Tv",2527,4.650178,2397,90,40,94.855560,3.561535,1.582905
64,Fire Tablets,"Fire HD 8 Tablet with Alexa, 8 HD Display, 16 ...",2442,4.596233,2324,74,44,95.167895,3.030303,1.801802
45,Fire Tablets,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",2275,4.587253,2153,77,45,94.637363,3.384615,1.978022
68,Fire Tablets,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",1680,4.513690,1527,91,62,90.892857,5.416667,3.690476
69,Fire Tablets,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",1663,4.530968,1518,91,54,91.280818,5.472038,3.247144
67,Fire Tablets,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",1485,4.536700,1359,77,49,91.515152,5.185185,3.299663
73,Fire Tablets,"Fire Tablet, 7 Display, Wi-Fi, 16 GB - Include...",1021,4.507346,943,45,33,92.360431,4.407444,3.232125
60,Fire Tablets,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...,973,4.533402,900,45,28,92.497431,4.624872,2.877698
43,Fire Tablets,"All-New Fire HD 8 Tablet with Alexa, 8 HD Disp...",882,4.578231,822,45,15,93.197279,5.102041,1.700680
99,Smart Speakers & Echo,Amazon Echo Show Alexa-enabled Bluetooth Speak...,843,4.661922,797,31,15,94.543298,3.677343,1.779359
71,Fire Tablets,"Fire Tablet with Alexa, 7 Display, 16 GB, Mage...",663,4.509804,614,28,21,92.609351,4.223228,3.167421
39,E-readers & Kindle,"Kindle Voyage E-reader, 6 High-Resolution Disp...",593,4.747049,575,14,4,96.964587,2.360877,0.674536
93,Smart Speakers & Echo,Amazon - Echo Plus w/ Built-In Hub - Silver,590,4.749153,568,14,8,96.271186,2.372881,1.355932
62,Fire Tablets,"Echo (White), Echo (White)",403,4.441687,359,29,15,89.081886,7.196030,3.722084

## 7. Weighted product ranking

Instead of ranking only by average rating, use a Bayesian-style weighted rating:

`weighted = (v/(v+m))*R + (m/(v+m))*C`

This reduces the chance that a product with only a few high ratings becomes the top recommendation.

In [14]:
C = data["reviews.rating"].mean()
m_reviews = max(3, int(product_stats["review_count"].quantile(0.25)))

product_stats["weighted_rating"] = (
    product_stats["review_count"]
    / (product_stats["review_count"] + m_reviews)
    * product_stats["average_rating"]
    +
    m_reviews
    / (product_stats["review_count"] + m_reviews)
    * C
)

def category_products(category):
    return product_stats[
        product_stats["kmeans_category"] == category
    ].copy()

def top_products(category, n=3):
    return (
        category_products(category)
        .sort_values(
            ["weighted_rating", "review_count"],
            ascending=[False, False]
        )
        .head(n)
    )

def weakest_product(category):
    p = category_products(category)
    if p.empty:
        return None

    return (
        p.sort_values(
            ["weighted_rating", "negative_pct"],
            ascending=[True, False]
        )
        .head(1)
    )

print("Global rating mean:", round(C, 3))
print("m:", m_reviews)

Global rating mean: 4.542
m: 3

## 8. Inspect ranked products

In [15]:
for category in data["kmeans_category"].drop_duplicates():

    print("\n" + "=" * 100)
    print(category)

    display(
        top_products(category)[
            [
                PRODUCT_COLUMN,
                "review_count",
                "average_rating",
                "weighted_rating",
                "positive_pct",
                "negative_pct"
            ]
        ]
    )

====================================================================================================
Fire Tablets

,product_name_clean,review_count,average_rating,weighted_rating,positive_pct,negative_pct
51,"All-New Fire HD 8 Tablet, 8"" HD Display, Wi-Fi...",3,5.00,4.771009,100.0,0.0
58,Amazon Kindle Touch Leather Case (4th Generati...,3,5.00,4.771009,100.0,0.0
53,Amazon - Kindle Voyage - 4GB - Wi-Fi + 3G - Bl...,25,4.72,4.700931,96.0,0.0

====================================================================================================
E-readers & Kindle

,product_name_clean,review_count,average_rating,weighted_rating,positive_pct,negative_pct
24,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...,59,4.830508,4.816549,100.000000,0.000000
29,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",52,4.826923,4.811383,98.076923,1.923077
27,Certified Refurbished Amazon Fire TV with Alex...,4,5.000000,4.803722,100.000000,0.000000

====================================================================================================
Streaming & TV

,product_name_clean,review_count,average_rating,weighted_rating,positive_pct,negative_pct
125,Fire TV Stick Streaming Media Player Pair Kit,6,5.0,4.847339,100.0,0.0
121,Amazon Fire TV with 4K Ultra HD and Alexa Voic...,4,5.0,4.803722,100.0,0.0
123,Brand New Amazon Kindle Fire 16gb 7 Ips Displa...,1,5.0,4.656514,100.0,0.0

====================================================================================================
Chargers & Cables

,product_name_clean,review_count,average_rating,weighted_rating,positive_pct,negative_pct
4,AmazonBasics USB 3.0 Cable - A-Male to B-Male ...,6,5.0,4.847339,100.0,0.0
2,AmazonBasics 16-Gauge Speaker Wire - 100 Feet,5,5.0,4.828257,100.0,0.0
6,Kindle PowerFast International Charging Kit (f...,5,4.8,4.703257,100.0,0.0

====================================================================================================
Smart Speakers & Echo

,product_name_clean,review_count,average_rating,weighted_rating,positive_pct,negative_pct
109,Certified Refurbished Amazon Echo,7,5.000000,4.862605,100.000,0.00000
112,"Echo (Black), Echo (Black)",3,5.000000,4.771009,100.000,0.00000
101,"Amazon Fire Hd 10 Tablet, Wi-Fi, 16 Gb, Specia...",128,4.773438,4.768138,96.875,0.78125

====================================================================================================
Household, Office & Pets

,product_name_clean,review_count,average_rating,weighted_rating,positive_pct,negative_pct
89,Expanding Accordion File Folder Plastic Portab...,9,5.0,4.885505,100.0,0.0
88,Cat Litter Box Covered Tray Kitten Extra Large...,2,5.0,4.725211,100.0,0.0
84,AmazonBasics Nespresso Pod Storage Drawer - 50...,1,5.0,4.656514,100.0,0.0

# Complaint Analysis

## 9. Negative reviews

In [17]:
negative_reviews = (
    data[data["sentiment"] == "negative"]
    .drop_duplicates(
        subset=[
            "kmeans_category",
            PRODUCT_COLUMN,
            "review_clean"
        ]
    )
    .copy()
)

print("Negative reviews:", len(negative_reviews))

Negative reviews: 2161

## 10. Extract complaint themes with TF-IDF

The strongest words and bigrams from negative reviews become **candidate complaint themes**.

In [19]:
def extract_complaint_terms(category, n_terms=10):

    reviews = (
        negative_reviews[
            negative_reviews["kmeans_category"] == category
        ]["review_clean"]
        .drop_duplicates()
    )

    if len(reviews) < 2:
        return []

    vectorizer = TfidfVectorizer(
        stop_words="english",
        ngram_range=(1, 2),
        min_df=1,
        max_df=0.95,
        sublinear_tf=True
    )

    X = vectorizer.fit_transform(reviews)

    terms = np.array(vectorizer.get_feature_names_out())
    scores = np.asarray(X.mean(axis=0)).ravel()

    top_indices = scores.argsort()[-n_terms:][::-1]

    return [
        (terms[i], float(scores[i]))
        for i in top_indices
    ]

for category in data["kmeans_category"].drop_duplicates():
    print("\n", category)
    print(extract_complaint_terms(category))

 Fire Tablets
[('tablet', 0.026468105571596488), ('amazon', 0.019908795714560928), ('bought', 0.015921032665102423), ('good', 0.015388684442699219), ('slow', 0.01537701113086478), ('apps', 0.015040591559904346), ('use', 0.014368936437912339), ('buy', 0.013492898275075686), ('like', 0.013285891585606164), ('screen', 0.01295801786857888)]

 E-readers & Kindle
[('kindle', 0.0336436967170532), ('buy', 0.02350508368482941), ('charge', 0.020102835458568055), ('read', 0.02004384710592899), ('books', 0.018992039690421535), ('charger', 0.017675273727569683), ('expensive', 0.016992545248853574), ('amazon', 0.01677311539450927), ('just', 0.016463990633299463), ('work', 0.015667256520710795)]

 Streaming & TV
[('amazon', 0.07461412820791982), ('refurbished', 0.07370504563840237), ('bought', 0.07211451893023704), ('box', 0.06784851644643981), ('tv', 0.06475627884193569), ('certified', 0.06346742732050384), ('boot', 0.05617197961301268), ('new', 0.04930719629598497), ('amazon logo', 0.046998678085051745), ('logo', 0.046998678085051745)]

 Chargers & Cables
[('kindle', 0.059858779042648955), ('amazon', 0.05823214086082023), ('cord', 0.0497490259495863), ('charger', 0.046368924408053167), ('bought', 0.03901685699944452), ('use', 0.03573739757223025), ('just', 0.03423439981112576), ('charge', 0.032030886342453116), ('replacement', 0.030442295391488933), ('charging', 0.03000207313915933)]

 Smart Speakers & Echo
[('alexa', 0.02513800003299523), ('questions', 0.02097297973502383), ('google', 0.019790180851411578), ('home', 0.019126817480179498), ('work', 0.019083119555098067), ('answer', 0.01888322833189033), ('amazon', 0.018835381769525133), ('device', 0.018747323685586896), ('like', 0.018532410711254402), ('echo', 0.018420974523378708)]

 Household, Office & Pets
[('batteries', 0.04388080587272228), ('long', 0.03083890456552672), ('don', 0.026458177744906847), ('work', 0.016812139234382552), ('buy', 0.01640105834643397), ('battery', 0.014888757075539003), ('dead', 0.01475814151903101), ('amazon', 0.014626866153831922), ('use', 0.013547000499898673), ('don long', 0.01350814265591026)]

## 11. Representative negative-review excerpts

In [21]:
def negative_examples(category, n=6):

    subset = negative_reviews[
        negative_reviews["kmeans_category"] == category
    ].copy()

    subset = subset[
        subset["review_clean"].str.len() >= 25
    ]

    subset["length"] = subset["review_clean"].str.len()

    return (
        subset.sort_values("length", ascending=False)
        .head(n)[
            [
                PRODUCT_COLUMN,
                "reviews.rating",
                "review_clean"
            ]
        ]
    )

for category in data["kmeans_category"].drop_duplicates():

    print("\n", category)

    display(
        negative_examples(category)
    )

 Fire Tablets

,product_name_clean,reviews.rating,review_clean
6383,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",1.0,"It's very appealing for the price, but know in..."
53237,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",1.0,I went with this tablet based on many good cus...
727,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",1.0,I went with this tablet based on many good cus...
60471,"Fire HD 8 Tablet with Alexa, 8 HD Display, 16 ...",1.0,I went with this tablet based on many good cus...
13978,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",2.0,"We bought WowWee MiP robots for our grandsons,..."
14329,"Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes...",2.0,"I didn't expect a lot at this price, but I als..."

 E-readers & Kindle

,product_name_clean,reviews.rating,review_clean
18209,Amazon Kindle Paperwhite - eBook reader - 4 GB...,2.0,I wanted to like this a lot because my Ipad Mi...
15774,"Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16...",2.0,"I don't want to get too negative on this, beca..."
57178,All-New Kindle Oasis E-reader - 7 High-Resolut...,2.0,"I've always been a fan of the Kindle, ever sin..."
20837,"Kindle Voyage E-reader, 6 High-Resolution Disp...",1.0,"Very disappointed that my Kindle Voyage, purch..."
19734,Amazon Kindle Paperwhite - eBook reader - 4 GB...,2.0,I am on my 3rd Kindle. This software downloads...
20251,Amazon Kindle Paperwhite - eBook reader - 4 GB...,1.0,Used it for 2 days and the screen froze 5 time...

 Streaming & TV

,product_name_clean,reviews.rating,review_clean
45901,AmazonBasics Nylon CD/DVD Binder (400 Capacity),2.0,My initial impression of this was very good. T...
21569,"Echo (White), Echo (White)",2.0,I bought this thing refurbished. I find that I...
21562,"Echo (White), Echo (White)",1.0,Stay away from the certified refurbished Amazo...
21567,"Echo (White), Echo (White)",1.0,Certified garbage! Lesson learned about paying...
21566,"Echo (White), Echo (White)",1.0,I bought this thinking since we'd bought sever...

 Chargers & Cables

,product_name_clean,reviews.rating,review_clean
49724,Amazon Kindle Charger Power Adapter Wall Charg...,2.0,"When I got my Kindle Fire, I got a protective ..."
49763,Oem Amazon Kindle Power Usb Adapter Wall Trave...,1.0,"No reason. This product is described as 5W, 1 ..."
49762,Oem Amazon Kindle Power Usb Adapter Wall Trave...,1.0,One star because this should've been included ...
58403,Amazon Kindle Replacement Power Adapter (Fits ...,2.0,I purchased my Kindle2 in March of 09 - and it...
58404,Amazon Kindle Replacement Power Adapter (Fits ...,1.0,Can someone explain to me why I can find hundr...
58401,Amazon Kindle Replacement Power Adapter (Fits ...,1.0,I was initially happy that my Kindle replaceme...

 Smart Speakers & Echo

,product_name_clean,reviews.rating,review_clean
27374,"Amazon Fire Tv, Amazon Fire Tv",1.0,Bestbuy came through before the holiday better...
26896,"Amazon Fire Tv, Amazon Fire Tv",2.0,I received this as a Christmas gift. I was exc...
23477,"Echo (White), Echo (White)",2.0,I bought this to fill my life with music. The ...
25313,Amazon - Amazon Tap Portable Bluetooth and Wi-...,1.0,I was excited about the Amazon echo. However a...
49742,Amazon Tap Smart Assistant Alexaenabled (black...,2.0,"Like DOS, you need to memorize your command an..."
27162,"Amazon Fire Tv, Amazon Fire Tv",1.0,I purchased this item on the recommendation of...

 Household, Office & Pets

,product_name_clean,reviews.rating,review_clean
48763,AmazonBasics AA Performance Alkaline Batteries...,2.0,I am extremely disappointed with these batteri...
42379,AmazonBasics AAA Performance Alkaline Batterie...,2.0,"So, I purchased a pack of these a month ago (1..."
48704,AmazonBasics AA Performance Alkaline Batteries...,2.0,"A day or two after these batteries arrived, I ..."
43773,AmazonBasics AAA Performance Alkaline Batterie...,2.0,"A day or two after these batteries arrived, I ..."
38302,AmazonBasics AAA Performance Alkaline Batterie...,1.0,These are the WORST batteries I have ever enco...
45562,AmazonBasics AAA Performance Alkaline Batterie...,1.0,I came here to look at the one and two star re...

# Build Evidence for the LLM

## 12. Structured evidence package

In [22]:
def build_evidence(category):

    subset = data[
        data["kmeans_category"] == category
    ]

    return {
        "category": category,
        "review_count": len(subset),
        "product_count": subset[PRODUCT_COLUMN].nunique(),
        "average_rating": subset["reviews.rating"].mean(),
        "top_products": top_products(category, 3),
        "weakest": weakest_product(category),
        "complaint_terms": extract_complaint_terms(category, 10),
        "negative_examples": negative_examples(category, 6)
    }

evidence = {
    category: build_evidence(category)
    for category in data["kmeans_category"].drop_duplicates()
}

example_category = next(iter(evidence))

print("Evidence packages:", len(evidence))
print("Example category:", example_category)

Evidence packages: 6
Example category: Fire Tablets

## 13. Grounded prompt

In [23]:
def build_prompt(e):

    lines = [
        "Write a detailed consumer recommendation article from the Amazon review evidence below.",
        "",
        "STRICT RULES:",
        "- Use ONLY the supplied evidence.",
        "- Never invent specifications, features, prices or complaints.",
        "- Keep all numerical claims consistent with the supplied data.",
        "- Treat TF-IDF complaint terms as candidate themes and verify them against review excerpts.",
        "- If evidence is insufficient, explicitly say so.",
        "",
        f"CATEGORY: {e['category']}",
        (
            f"DATA: {e['product_count']} products; "
            f"{e['review_count']} reviews; "
            f"category average rating={e['average_rating']:.2f}/5."
        ),
        "",
        "TOP PRODUCTS:"
    ]

    for rank, (_, row) in enumerate(
        e["top_products"].iterrows(), 1
    ):
        lines.append(
            f"{rank}. {row[PRODUCT_COLUMN]} | "
            f"reviews={int(row['review_count'])} | "
            f"rating={row['average_rating']:.2f}/5 | "
            f"weighted rating={row['weighted_rating']:.2f}/5 | "
            f"positive={row['positive_pct']:.1f}% | "
            f"negative={row['negative_pct']:.1f}%"
        )

    weakest = e["weakest"]

    if weakest is not None and not weakest.empty:
        row = weakest.iloc[0]

        lines += [
            "",
            "WEAKEST PRODUCT BY WEIGHTED EVIDENCE:",
            (
                f"{row[PRODUCT_COLUMN]} | "
                f"reviews={int(row['review_count'])} | "
                f"rating={row['average_rating']:.2f}/5 | "
                f"weighted rating={row['weighted_rating']:.2f}/5 | "
                f"negative={row['negative_pct']:.1f}%"
            )
        ]

    lines += [
        "",
        "CANDIDATE COMPLAINT THEMES:"
    ]

    if e["complaint_terms"]:
        for term, score in e["complaint_terms"]:
            lines.append(f"- {term}")
    else:
        lines.append("- insufficient negative-review evidence")

    lines += [
        "",
        "NEGATIVE REVIEW EVIDENCE:"
    ]

    for _, row in e["negative_examples"].iterrows():
        lines.append(
            f"- {row[PRODUCT_COLUMN]} "
            f"({row['reviews.rating']}/5): "
            f"{row['review_clean'][:450]}"
        )

    lines += [
        "",
        "WRITE EXACTLY THESE SECTIONS:",
        "## Category Overview",
        "## Top 3 Products",
        "## Key Differences",
        "## Common Customer Complaints",
        "## Weakest Product",
        "## Final Recommendation",
        "",
        "Explain conclusions with the supplied evidence.",
        "Aim for approximately 400-600 words."
    ]

    return "\n".join(lines)

print(build_prompt(evidence[example_category]))

Write a detailed consumer recommendation article from the Amazon review evidence below.

STRICT RULES:
- Use ONLY the supplied evidence.
- Never invent specifications, features, prices or complaints.
- Keep all numerical claims consistent with the supplied data.
- Treat TF-IDF complaint terms as candidate themes and verify them against review excerpts.
- If evidence is insufficient, explicitly say so.

CATEGORY: Fire Tablets
DATA: 37 products; 29370 reviews; category average rating=4.52/5.

TOP PRODUCTS:
1. All-New Fire HD 8 Tablet, 8" HD Display, Wi-Fi, 16 GB - Includes Special Offers, Magenta | reviews=3 | rating=5.00/5 | weighted rating=4.77/5 | positive=100.0% | negative=0.0%
2. Amazon Kindle Touch Leather Case (4th Generation - 2011 Release), Olive Green, Amazon Kindle Touch Leather Case (4th Generation - 2011 Release), Olive Green | reviews=3 | rating=5.00/5 | weighted rating=4.77/5 | positive=100.0% | negative=0.0%
3. Amazon - Kindle Voyage - 4GB - Wi-Fi + 3G - Black, Amazon - Kindle Voyage - 4GB - Wi-Fi + 3G - Black | reviews=25 | rating=4.72/5 | weighted rating=4.70/5 | positive=96.0% | negative=0.0%

WEAKEST PRODUCT BY WEIGHTED EVIDENCE:
Kindle Oasis E-reader with Leather Charging Cover - Black, 6 High-Resolution Display (300 ppi), Wi-Fi - Includes Special Offers | reviews=6 | rating=3.83/5 | weighted rating=4.07/5 | negative=16.7%

CANDIDATE COMPLAINT THEMES:
- tablet
- amazon
- bought
- good
- slow
- apps
- use
- buy
- like
- screen

NEGATIVE REVIEW EVIDENCE:
- Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes Special Offers, Magenta (1.0/5): It's very appealing for the price, but know in advance that the warranty is only 90 days... I did not. So when my sons device stopped charging due to a lose charging port a little over 2 months after he got it, I didn't rush to call. I have been taking care of seriously ill family members so I put customer service on the bottom of my list of priorities since I thought I had time,,, especially knowing that these types of calls can sometimes take h
- All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi, 16 GB - Includes Special Offers, Black (1.0/5): I went with this tablet based on many good customer reviews, but my experience was not a good one. From the start I was on the phone every day for at least an hour with Amazon tech support for one issue or another. Most of the techs were very polite, but not all knew the product very well. At one point I asked one of them about trying to save some RAM and they kept referring me to the storage, which told me they didn't even know the difference be
- All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi, 16 GB - Includes Special Offers, Magenta (1.0/5): I went with this tablet based on many good customer reviews, but my experience was not a good one. From the start I was on the phone every day for at least an hour with Amazon tech support for one issue or another. Most of the techs were very polite, but not all knew the product very well. At one point I asked one of them about trying to save some RAM and they kept referring me to the storage, which told me they didn't even know the difference be
- Fire HD 8 Tablet with Alexa, 8 HD Display, 16 GB, Tangerine - with Special Offers (1.0/5): I went with this tablet based on many good customer reviews, but my experience was not a good one. From the start I was on the phone every day for at least an hour with Amazon tech support for one issue or another. Most of the techs were very polite, but not all knew the product very well. At one point I asked one of them about trying to save some RAM and they kept referring me to the storage, which told me they didn't even know the difference be
- Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes Special Offers, Magenta (2.0/5): We bought WowWee MiP robots for our grandsons, 8 and 11 years old. They don't have iPad or iPhone in their home. So thoroughly researched what else would work for installing the app. Talked with Best Buy salesperson, who said the app could be loaded via the app store (it can't).Kindle Fire 2015 is included on the WowWee "compatibility" list. So we bought them each a brand new Kindle in order to use the app. They had Kindles from earlier years, bu
- Fire Tablet, 7 Display, Wi-Fi, 8 GB - Includes Special Offers, Magenta (2.0/5): I didn't expect a lot at this price, but I also did not expect both of my tablets to be riddled with dead/stuck pixels right out of the box. I have a third arriving in the mail and am just praying that I am at least good for 1/3. Waiting on its arrival before doing the trip for return/replacement just in case that one needs to go as well. Maybe just bad luck, but definitely worth noting for anyone who may also be inconvenienced by having to do a

WRITE EXACTLY THESE SECTIONS:
## Category Overview
## Top 3 Products
## Key Differences
## Common Customer Complaints
## Weakest Product
## Final Recommendation

Explain conclusions with the supplied evidence.
Aim for approximately 400-600 words.

# Generative AI

## 14. Load Qwen2.5-1.5B-Instruct

This replaces FLAN-T5 and does not use `text2text-generation`.

In [24]:
MODEL_NAME = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype="auto",
    device_map="auto"
)

model.eval()

print("Loaded:", MODEL_NAME)

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 3.09GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Loaded: Qwen/Qwen2.5-1.5B-Instruct

## 15. Article generation function

In [25]:
def generate_article(category, max_new_tokens=700):

    messages = [
        {
            "role": "system",
            "content": (
                "You are a careful product-review analyst. "
                "Use only supplied evidence. "
                "Never invent unsupported product facts."
            )
        },
        {
            "role": "user",
            "content": build_prompt(
                evidence[category]
            )
        }
    ]

    formatted = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        formatted,
        return_tensors="pt",
        truncation=True,
        max_length=4096
    )

    inputs = {
        key: value.to(model.device)
        for key, value in inputs.items()
    }

    with torch.no_grad():

        output = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=0.3,
            top_p=0.9,
            repetition_penalty=1.08,
            pad_token_id=tokenizer.eos_token_id
        )

    generated_tokens = output[
        0,
        inputs["input_ids"].shape[1]:
    ]

    return tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    ).strip()

## 16. Test one category first

In [ ]:
print("Generating:", example_category)

example_article = generate_article(
    example_category
)

print("\n" + "=" * 100)
print(example_article)

## 17. Generate all category articles

In [26]:
generated = []

for category in evidence:

    print("Generating:", category)

    try:
        article = generate_article(category)
        status = "success"

    except Exception as error:
        article = ""
        status = str(error)

    generated.append({
        "kmeans_category": category,
        "generated_article": article,
        "status": status
    })

articles = pd.DataFrame(generated)

display(articles)

Generating: Fire Tablets
Generating: E-readers & Kindle
Generating: Streaming & TV
Generating: Chargers & Cables
Generating: Smart Speakers & Echo
Generating: Household, Office & Pets

,kmeans_category,generated_article,status
0,Fire Tablets,### Category Overview\n\nThe Fire Tablets cate...,success
1,E-readers & Kindle,### Category Overview\nThe Amazon Kindle serie...,success
2,Streaming & TV,### Category Overview\nThe streaming and telev...,success
3,Chargers & Cables,### Category Overview\n\nThe Amazon review dat...,success
4,Smart Speakers & Echo,### Category Overview\n\nThe Smart Speakers & ...,success
5,"Household, Office & Pets","### Category Overview\nThe household, office, ...",success

## 18. Inspect all generated articles

In [27]:
for _, row in articles.iterrows():

    print("\n" + "=" * 110)
    print(row["kmeans_category"])
    print("=" * 110)

    print(row["generated_article"])

==============================================================================================================
Fire Tablets
==============================================================================================================
### Category Overview

The Fire Tablets category offers a range of options from different manufacturers, catering to various user preferences and requirements. The average rating across 37 products reviewed is 4.52/5, indicating generally high satisfaction among users. This suggests that the majority of customers find value in these devices, although there are notable exceptions.

### Top 3 Products

#### 1. All-New Fire HD 8 Tablet, 8" HD Display, Wi-Fi, 16 GB - Includes Special Offers, Magenta
**Reviews:** 3
**Rating:** 5.00/5
**Weighted Rating:** 4.77/5
**Positive:** 100.0%
**Negative:** 0.0%

This product stands out as the highest-rated option, receiving perfect scores across all metrics. Customers appreciate its 8-inch display, Wi-Fi connectivity, and ample storage capacity. The inclusion of special offers adds convenience for potential buyers.

#### 2. Amazon Kindle Touch Leather Case (4th Generation - 2011 Release), Olive Green
**Reviews:** 3
**Rating:** 5.00/5
**Weighted Rating:** 4.77/5
**Positive:** 100.0%
**Negative:** 0.0%

Another standout product, this leather case provides excellent protection for the Kindle Touch while maintaining a sleek design. It has received unanimous praise from reviewers.

#### 3. Amazon - Kindle Voyage - 4GB - Wi-Fi + 3G - Black
**Reviews:** 25
**Rating:** 4.72/5
**Weighted Rating:** 4.70/5
**Positive:** 96.0%
**Negative:** 0.0%

The Kindle Voyage is favored for its balance between storage capacity and connectivity options. While slightly lower than the top two products, it still delivers solid performance and reliability.

### Key Differences

When comparing the top three products, several key differences emerge:

1. **Display Size**: The All-New Fire HD 8 Tablet stands out with its larger 8-inch display compared to the other two models.
2. **Storage Capacity**: The Kindle Voyage offers more storage space (4GB) than the others, making it suitable for those needing additional memory.
3. **Connectivity Options**: The Kindle Voyage supports Wi-Fi and 3G, providing better versatility depending on the user’s location and needs.
4. **Design and Protection**: Both the All-New Fire HD 8 Tablet and the Kindle Voyage come with protective cases, enhancing durability and ease of use.

### Common Customer Complaints

Despite the overall positive reception, several common complaints are noted in the reviews:

1. **Warranty Issues**: Multiple reviews mention dissatisfaction with the warranty period, ranging from 90 days to no warranty at all.
2. **Customer Service**: Many users report long wait times and inconsistent technical knowledge from customer service representatives.
3. **Pixel Issues**: Dead or stuck pixels are frequently reported, particularly in the first few weeks of ownership.
4. **App Compatibility**: Some users struggle with app loading issues, especially if the device is not compatible with certain applications.

### Weakest Product

The weakest product by weighted evidence is the Kindle Oasis E-reader with Leather Charging Cover - Black, 6 High-Resolution Display (300 ppi), Wi

==============================================================================================================
E-readers & Kindle
==============================================================================================================
### Category Overview
The Amazon Kindle series offers a range of devices catering to different needs and preferences. From basic readers to advanced models with additional features, the Kindle lineup provides users with various options to suit their reading habits and requirements. The Kindle Fire series, including the Fire Tablet and Fire TV, has gained popularity among consumers who prefer tablets for both reading and entertainment. The Kindle Oasis and Kindle Voyage offer more advanced features such as waterproof capabilities and adaptive lighting, making them suitable for outdoor use and specific reading environments. The Kindle Paperwhite is known for its high-resolution e-paper display and long-lasting battery life, while the Kindle Kids Edition tablet is designed specifically for children, offering safety features and educational content.

### Top 3 Products
Among the top-rated products, the **Amazon Kindle Fire 16GB 7-inch Display Tablet** stands out with a perfect rating of 4.83/5. This model is praised for its lightweight design, allowing users to easily carry it around without feeling weighed down. Another highly recommended option is the **Fire Tablet**, which received a rating of 4.83/5. This tablet is favored for its 7-inch display, Wi-Fi connectivity, and the inclusion of special offers. Lastly, the **Certified Refurbished Amazon Fire TV with Alexa Voice Remote** also receives excellent ratings, with a perfect score of 5.00/5. This model is appreciated for its Alexa voice remote control, providing convenient access to voice commands.

### Key Differences
While all these devices share some common features—such as Wi-Fi connectivity, touchscreens, and e-paper displays—the differences lie in their storage capacity, physical design, and additional features. For instance, the **Kindle Oasis** offers a higher storage capacity of 8GB compared to the Fire Tablet, making it ideal for those who need more storage for larger collections of eBooks. The **Kindle Voyage** boasts a high-resolution display and built-in audio, enhancing the reading experience with adaptive lighting and page press sensors. On the other hand, the **Kindle Kids Edition Tablet** is specifically designed for children, featuring kid-proof cases and educational content tailored for young readers.

### Common Customer Complaints
Despite their numerous advantages, several customers have reported issues with these devices. One common theme among complaints is the presence of advertisements during certain activities, such as when the device is in sleep mode. Customers have expressed frustration with the intrusive ads, especially considering the cost difference between the standard version and the premium edition. Another issue frequently mentioned is the difficulty in accessing certain features or services, leading to dissatisfaction with the overall user experience.

### Weakest Product
One of the weakest products by weighted evidence is the **Fire Kids Edition Tablet, 7 Display, Wi-Fi, 16 GB, Green Kid-Proof Case**. With a rating of 3.67/5 and a weighted rating of 3.96/5, this tablet is criticized for its lack of durability and functionality. Customers report that the case is prone to damage, particularly if dropped or subjected to rough handling. Additionally, the tablet struggles with charging issues, often failing to power on or require frequent resets, despite its advertised features. These problems highlight significant shortcomings in the product's design and build quality, making it a poor choice for users seeking reliable performance and longevity.

### Final Recommendation
Given the strong performance and customer satisfaction of the top-rated products, such as the **Amazon Kindle Fire

==============================================================================================================
Streaming & TV
==============================================================================================================
### Category Overview
The streaming and television market offers a wide range of devices designed to enhance user experience through various functionalities such as video playback, voice control, and connectivity options. This review focuses on three top-rated products from the Amazon platform—Fire TV Stick, Amazon Fire TV with 4K Ultra HD and Alexa Voice Remote, and a brand new Amazon Kindle Fire tablet. These devices cater to different preferences and requirements, including entertainment, productivity, and connectivity.

### Top 3 Products
#### Fire TV Stick Streaming Media Player Pair Kit
**Reviews:** 6
**Rating:** 5.00/5
**Weighted Rating:** 4.85/5
**Positive:** 100.0%
**Negative:** 0.0%

This product stands out due to its high rating and positive feedback across multiple reviews. Users appreciate its compatibility with various devices, its robust performance, and its seamless integration with Amazon services. The Fire TV Stick's ability to stream content from multiple platforms and its support for both standard and 4K resolutions make it a versatile choice for those looking to enjoy high-quality video content.

#### Amazon Fire TV with 4K Ultra HD and Alexa Voice Remote (Pendant Design)
**Reviews:** 4
**Rating:** 5.00/5
**Weighted Rating:** 4.80/5
**Positive:** 100.0%
**Negative:** 0.0%

Another standout product, this model offers superior 4K resolution and enhanced audio capabilities. Its pendant design adds a stylish touch while maintaining functionality. Users praise its ease of use, especially with the Alexa voice remote, which simplifies navigation and interaction with the device.

#### Brand New Amazon Kindle Fire 16GB 7" Display Tablet WiFi 16 GB Blue
**Reviews:** 1
**Rating:** 5.00/5
**Weighted Rating:** 4.66/5
**Positive:** 100.0%
**Negative:** 0.0%

For those seeking a more traditional reading experience, the Kindle Fire offers a smooth and fast browsing experience. Its large display and built-in Wi-Fi connectivity make it ideal for digital reading and light internet usage. The device also includes a blue light filter, enhancing its suitability for extended periods of use.

### Key Differences
While these devices share some common features, they differ significantly in their specific strengths and target audience:

- **Fire TV Stick**: Primarily aimed at users who value versatility and broad compatibility, offering both standard and 4K streaming options.
- **Amazon Fire TV with 4K Ultra HD and Alexa Voice Remote**: Focused on delivering premium 4K content and enhanced voice control, making it suitable for media enthusiasts and tech-savvy users.
- **Kindle Fire**: Designed for dedicated readers and digital content consumers, emphasizing long battery life and a comfortable viewing experience.

### Common Customer Complaints
Despite their popularity, customers occasionally report issues related to connectivity and reliability. Here are some recurring complaints:

- **Amazon Basics Nylon CD/DVD Binder (400 Capacity)**: While generally well-received, some users found the material less durable than expected, particularly after repeated use.
- **Echo (White), Echo (White)**: Several reviews highlight problems with the device's ability to connect to the TV, requiring frequent reconnection efforts. Some users also reported issues

==============================================================================================================
Chargers & Cables
==============================================================================================================
### Category Overview

The Amazon review dataset for "Chargers & Cables" contains 8 products across 56 reviews, with an average rating of 4.23/5. This indicates a generally positive experience among consumers. However, there are notable variations in customer satisfaction, particularly regarding the Amazon Kindle Power Fast International Charging Kit, which receives the lowest weighted rating of 2.52/5.

### Top 3 Products

#### 1. AmazonBasics USB 3.0 Cable - A-Male to B-Male - 6 Feet (1.8 Meters)
- **Reviews:** 6
- **Rating:** 5.00/5
- **Weighted Rating:** 4.85/5
- **Positive:** 100.0%
- **Negative:** 0.0%

This product stands out as the top choice with the highest weighted rating, indicating exceptional performance. Customers report no issues with the cable, suggesting it meets their needs perfectly.

#### 2. AmazonBasics 16-Gauge Speaker Wire - 100 Feet
- **Reviews:** 5
- **Rating:** 5.00/5
- **Weighted Rating:** 4.83/5
- **Positive:** 100.0%
- **Negative:** 0.0%

Similar to the USB cable, this speaker wire also receives the highest weighted rating. Customers appreciate its durability and effectiveness in delivering clear audio signals.

#### 3. Kindle PowerFast International Charging Kit (for accelerated charging in over 200 countries)
- **Reviews:** 5
- **Rating:** 4.80/5
- **Weighted Rating:** 4.70/5
- **Positive:** 100.0%
- **Negative:** 0.0%

Customers praise this kit for its ability to accelerate charging times globally, making it convenient for international travelers. Its universal compatibility is highlighted as a significant advantage.

### Key Differences

While all products offer similar functionality—charging devices—the differences lie in specific features and user experiences. The AmazonBasics USB 3.0 Cable stands out due to its high-rated performance and reliability, whereas the Kindle PowerFast International Charging Kit offers unique benefits such as global acceleration and universal compatibility.

### Common Customer Complaints

Despite the overall positive sentiment, several common complaints emerge:

#### Kindle-related Issues
- **Kindle Charger Power Adapter Wall Charger And Usb Cable Micro Usb Cord (2.0/5):** Customers express frustration with the inability to keep the mini-USB cord in place, necessitating frequent replacements.
- **Oem Amazon Kindle Power Usb Adapter Wall Travel Charger Fire/dx/+micro Usb Cable (1.0/5):** Some users criticize the product's description as misleading, claiming it fails to meet the expected power output of 5W.
- **Oem Amazon Kindle Power Usb Adapter Wall Travel Charger Fire/dx/+micro Usb Cable (1.0/5):** Users complain about the lack of explanation for the discrepancy between the advertised 5W and actual performance.
- **Amazon Kindle Replacement Power Adapter (Fits Latest Generation Kindle and Kindle DX) For shipment in the U.S only (2.0/5):** Customers note the poor quality of the charging cord, leading to intermittent charging issues.
- **Amazon

==============================================================================================================
Smart Speakers & Echo
==============================================================================================================
### Category Overview

The Smart Speakers & Echo category on Amazon has garnered significant attention due to its popularity among consumers seeking intelligent voice assistants. With nearly 800 reviews and an average rating of 4.67/5, this category offers a wide range of devices designed to enhance connectivity and convenience in homes and offices. The primary focus areas include functionality, user experience, and compatibility with other smart home devices.

### Top 3 Products

#### 1. Certified Refurbished Amazon Echo
**Reviews:** 7
**Rating:** 5.00/5
**Weighted Rating:** 4.86/5
**Positive:** 100.0%
**Negative:** 0.0%

This product stands out as the highest-rated option, receiving perfect scores across all metrics. It is certified refurbished, ensuring a high-quality product at a discounted price. Users appreciate its reliability and ease of setup, making it a standout choice for those looking for a premium smart speaker without breaking the bank.

#### 2. Echo (Black)
**Reviews:** 3
**Rating:** 5.00/5
**Weighted Rating:** 4.77/5
**Positive:** 100.0%
**Negative:** 0.0%

Another top performer, the Echo (Black) offers excellent performance and customer satisfaction. Its sleek design and reliable operation make it a favorite among users who value both aesthetics and functionality. Despite having fewer reviews, this model consistently ranks highly based on user feedback.

#### 3. Amazon Fire HD 10 Tablet, Wi-Fi, 16 GB, Special Offers - Silver Aluminum
**Reviews:** 128
**Rating:** 4.77/5
**Weighted Rating:** 4.77/5
**Positive:** 96.9%
**Negative:** 0.8%

This tablet variant combines entertainment capabilities with smart home integration, appealing to tech enthusiasts and families alike. Its dual-purpose nature makes it versatile, catering to various needs such as streaming content and controlling smart home devices. The weighted rating reflects its strong performance and widespread adoption.

### Key Differences

While these three products share some commonalities—such as their ability to connect to other smart devices—the differences highlight unique strengths and weaknesses:

- **Certified Refurbished Amazon Echo vs. Echo (Black)**: The refurbished version offers a lower price point, potentially attracting budget-conscious buyers. In contrast, the black model provides a sleek, professional look and higher ratings, suggesting a slight edge in user satisfaction.
- **Echo (Black) vs. Amazon Fire HD 10 Tablet**: Both devices excel in their respective categories, offering robust smart home capabilities. However, the tablet's dual purpose and entertainment features might appeal to a broader audience, while the smart speaker focuses solely on voice control.

### Common Customer Complaints

Despite their overall success, several recurring issues have emerged in customer reviews:

- **Alexa Performance**: Many users report frustration with Alexa's responsiveness, particularly during initial setup. Some complain about delayed responses or inability to recognize certain commands correctly.
- **Google Integration**: There is a growing trend towards integrating with Google Assistant, leading to mixed opinions. While some users praise Google's simplicity, others express dissatisfaction with the lack of direct compatibility with Amazon's ecosystem.
- **Smart Home Compatibility**: Issues related to device discovery and configuration are prevalent,

==============================================================================================================
Household, Office & Pets
==============================================================================================================
### Category Overview
The household, office, and pets section offers a diverse range of products catering to various needs such as storage solutions, pet care essentials, and home appliances. This category includes items ranging from file folders and cat litter boxes to dog crates and electronic accessories. With an impressive 14 products reviewed across 12,139 reviews, the category stands out for its comprehensive coverage and user feedback.

### Top 3 Products
Among the top-rated products, the expanding accordion file folder plastic portable document organizer stands out with an exceptional rating of 5.00/5 and a weighted rating of 4.89/5. This versatile organizer boasts a letter size capacity, making it ideal for storing documents and papers. The overwhelming majority of users (100%) report satisfaction, indicating high reliability and functionality. The absence of any negative reviews further underscores the product's excellence.

In second place is the cat litter box covered tray kitten extra large enclosed hooded hidden toilet, also receiving a perfect score of 5.00/5. This product is highly praised for its durability and ease of use, particularly suitable for kittens and larger cats. Users appreciate the enclosed design, which helps maintain cleanliness and hygiene. The positive sentiment is evident throughout the reviews, suggesting a strong customer base.

Lastly, the AmazonBasics Nespresso pod storage drawer is another standout product, garnering a perfect 5.00/5 rating and a weighted rating of 4.66/5. This innovative storage solution is appreciated for its compact design and easy access to Nespresso pods. The positive reviews indicate that users find it convenient and effective for managing their coffee supply.

### Key Differences

## 19. Save the results

In [29]:
articles.to_csv(
    "category_recommendation_articles.csv",
    index=False
)

parts = [
    "# Amazon Product Review Recommendations\n"
]

for _, row in articles.iterrows():

    parts.append(
        f"## {row['kmeans_category']}\n"
    )

    parts.append(
        row["generated_article"] + "\n"
    )

Path(
    "product_recommendation_articles.md"
).write_text(
    "\n".join(parts),
    encoding="utf-8"
)

print("Saved category_recommendation_articles.csv")
print("Saved product_recommendation_articles.md")

Saved category_recommendation_articles.csv
Saved product_recommendation_articles.md

# Final Task 3 Methodology

```text
Task 2 meta-categories
        ↓
Category / product statistics
        ↓
Bayesian weighted product ranking
        ↓
Negative reviews
        ↓
TF-IDF complaint-theme extraction
        ↓
Representative complaint excerpts
        ↓
Structured evidence
        ↓
Grounded prompt
        ↓
Qwen2.5-1.5B-Instruct
        ↓
400–600 word recommendation articles
```

This design lets traditional NLP/statistical methods establish the evidence first and uses generative AI primarily for synthesis and readable recommendation writing.